"""First migration

Revision ID: c3a31aaccfa9
Revises: aab99b3ccfcc
Create Date: 2023-08-04 19:32:48.750874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a31aaccfa9'
down_revision: Union[str, None] = 'aab99b3ccfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_tags_id', table_name='book_tags')
    op.drop_table('book_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tags',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_tags_book_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='book_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', 'id', name='book_tags_pkey')
    )
    op.create_index('ix_book_tags_id', 'book_tags', ['id'], unique=False)
    # ### end Alembic commands ###
